sudo: false
language: node_js
node_js:
- '0.12.2'
install:
- npm install origami-build-tools@3.3.5 && make install
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- make test
